"""产业链图谱：16+ 条产业链的"下游→上游"拆解，找出每层供给松紧与卡脖子环节。

用法定位（产品宪法）：这是**教育性的结构地图**，不是荐股。
- 每层标注供给松紧：tight(卡点/少数玩家/难替代) / medium / loose(充分竞争);
- 列出代表性公司(illustrative, 非推荐)，可点进个股分析;
- 数据基于公开认知，可能过时/有误，看结构、不照抄。

供给紧的层 = 定价权/超额收益更可能藏的地方，常在不起眼的上游。
"""

# 每个 sector: key/name/emoji/category/hook/demand/layers[下游→上游]/takeaway
# layer: {layer,emoji,tightness,desc,chokepoint,players:[{ticker,name,role}]}
SECTORS = [
    {
        "key": "ai_datacenter", "name": "AI 数据中心", "emoji": "🤖", "category": "AI / 算力",
        "hook": "训练一个大模型的钱，最后流到了哪些不起眼的环节？",
        "demand": "AI 训练/推理算力需求（以 GPU 机柜、兆瓦电力计）",
        "layers": [
            {"layer": "云与大模型", "emoji": "☁️", "tightness": "medium",
             "desc": "买算力、训模型、卖 API/应用的最下游需求方，资金从这里出发。",
             "chokepoint": "", "players": [
                {"ticker": "MSFT", "name": "微软", "role": "Azure + OpenAI"},
                {"ticker": "GOOGL", "name": "谷歌", "role": "自研 TPU + 云"},
                {"ticker": "AMZN", "name": "亚马逊", "role": "AWS"}]},
            {"layer": "AI 加速芯片", "emoji": "🧠", "tightness": "tight",
             "desc": "GPU/加速卡，整条链的需求引擎，议价权极强。",
             "chokepoint": "英伟达近乎垄断训练市场，CUDA 生态是护城河——断供它，整条链停摆。",
             "players": [{"ticker": "NVDA", "name": "英伟达", "role": "训练 GPU 垄断"},
                         {"ticker": "AMD", "name": "AMD", "role": "MI 系列追赶"}]},
            {"layer": "供电与散热", "emoji": "🔌", "tightness": "tight",
             "desc": "机柜功率冲到 100kW+ 后，供电、液冷成了硬瓶颈，绕不开少数龙头。",
             "chokepoint": "Vertiv 在数据中心供电/液冷份额高、designed-in，是隐形卡点。",
             "players": [{"ticker": "VRT", "name": "Vertiv", "role": "供电/液冷龙头"},
                         {"ticker": "ETN", "name": "伊顿", "role": "电力管理"},
                         {"ticker": "MPWR", "name": "Monolithic", "role": "GPU 供电芯片"}]},
            {"layer": "高速互联与光", "emoji": "💡", "tightness": "tight",
             "desc": "集群越大，GPU 之间的连接(光模块/铜缆/交换)越是瓶颈。",
             "chokepoint": "光模块、AEC 有源铜缆产能紧，少数厂吃下大头。",
             "players": [{"ticker": "ANET", "name": "Arista", "role": "数据中心交换机"},
                         {"ticker": "CRDO", "name": "Credo", "role": "AEC 有源铜缆"},
                         {"ticker": "COHR", "name": "Coherent", "role": "光器件"}]},
            {"layer": "代工与先进封装", "emoji": "🏭", "tightness": "tight",
             "desc": "把芯片造出来、把 HBM 叠上去——最深的物理瓶颈。",
             "chokepoint": "台积电 CoWoS 先进封装产能是全行业的总闸门。",
             "players": [{"ticker": "TSM", "name": "台积电", "role": "先进制程+封装(ADR)"},
                         {"ticker": "ASML", "name": "ASML", "role": "EUV 光刻独家(ADR)"}]},
            {"layer": "上游电力", "emoji": "⚡", "tightness": "tight",
             "desc": "AI 真正的天花板是电。谁掌握稀缺、可调度的电力谁就有定价权。",
             "chokepoint": "可并网的大功率电力供给跟不上数据中心扩张，核电/燃机受益。",
             "players": [{"ticker": "VST", "name": "Vistra", "role": "独立电力(含核电)"},
                         {"ticker": "CEG", "name": "Constellation", "role": "核电运营"},
                         {"ticker": "GEV", "name": "GE Vernova", "role": "燃机/电网"}]},
        ],
        "takeaway": "下游(云/大模型)钱最多但竞争激烈；真正卡脖子在 GPU、CoWoS 封装、EUV、供电散热、和电力。越往上游越紧。",
    },
    {
        "key": "solar", "name": "太阳能", "emoji": "☀️", "category": "清洁能源",
        "hook": "组件价格年年崩，钱反而流向了'卖铲子'的设备和材料环节。",
        "demand": "全球新增光伏装机（GW）+ 配套储能",
        "layers": [
            {"layer": "电站与运营", "emoji": "🏞️", "tightness": "loose",
             "desc": "开发、建设、卖电。门槛低、玩家多，靠融资成本竞争。",
             "chokepoint": "", "players": [{"ticker": "NEE", "name": "NextEra", "role": "全球最大清洁电力"},
                                          {"ticker": "FSLR", "name": "First Solar", "role": "美国本土组件+电站"}]},
            {"layer": "逆变器", "emoji": "🔄", "tightness": "medium",
             "desc": "把直流变交流并网，带软件和服务粘性，比组件值钱。",
             "chokepoint": "", "players": [{"ticker": "ENPH", "name": "Enphase", "role": "微逆变器"},
                                          {"ticker": "SEDG", "name": "SolarEdge", "role": "优化器/逆变器"}]},
            {"layer": "电池片/组件", "emoji": "🔲", "tightness": "loose",
             "desc": "光伏的'大宗商品'，中国产能为主，长期价格战、利润薄。",
             "chokepoint": "", "players": [{"ticker": "FSLR", "name": "First Solar", "role": "薄膜(避开硅料战)"}]},
            {"layer": "多晶硅/硅片", "emoji": "🧊", "tightness": "medium",
             "desc": "上游材料，周期性强，扩产慢但终会过剩。",
             "chokepoint": "高纯多晶硅有技术与能耗壁垒，但产能周期决定盈利。",
             "players": [{"ticker": "DQ", "name": "大全新能源", "role": "多晶硅(ADR)"}]},
            {"layer": "设备与耗材", "emoji": "🛠️", "tightness": "tight",
             "desc": "造电池片/硅片的设备和高纯石英坩埚等耗材——'卖铲人'，最稳。",
             "chokepoint": "高端光伏设备与高纯石英砂供给集中，价格战里旱涝保收。",
             "players": [{"ticker": "AMAT", "name": "应用材料", "role": "镀膜/沉积设备"}]},
        ],
        "takeaway": "组件/电站是红海(loose)，别在那卷；钱在逆变器(软件粘性)和设备/耗材(卖铲)。这是'终端崩价、上游卖铲'的经典链。",
    },
    {
        "key": "nuclear", "name": "核能", "emoji": "☢️", "category": "清洁能源",
        "hook": "AI 抢电把核电从'夕阳'拽回'风口'，但真正稀缺的是燃料和审批。",
        "demand": "基荷清洁电力需求（数据中心、电网脱碳）",
        "layers": [
            {"layer": "核电运营", "emoji": "🏭", "tightness": "tight",
             "desc": "运营现有核电站卖电，AI 数据中心抢着签长协，议价权回归。",
             "chokepoint": "可运营的核电资产稀缺、审批极难新增，存量即护城河。",
             "players": [{"ticker": "CEG", "name": "Constellation", "role": "美国最大核电运营"},
                         {"ticker": "VST", "name": "Vistra", "role": "核电+燃机"}]},
            {"layer": "小型模块堆 SMR", "emoji": "🧩", "tightness": "medium",
             "desc": "下一代小堆，故事性强但多数尚未商业化，估值靠预期。",
             "chokepoint": "", "players": [{"ticker": "SMR", "name": "NuScale", "role": "SMR 设计"},
                                          {"ticker": "OKLO", "name": "Oklo", "role": "微堆(高风险)"}]},
            {"layer": "设备与建造", "emoji": "🏗️", "tightness": "medium",
             "desc": "反应堆、汽轮机、工程建造，重资产、长周期。",
             "chokepoint": "", "players": [{"ticker": "GEV", "name": "GE Vernova", "role": "核电设备"},
                                          {"ticker": "BWXT", "name": "BWX Tech", "role": "核组件/海军堆"}]},
            {"layer": "核燃料与浓缩", "emoji": "⚛️", "tightness": "tight",
             "desc": "铀浓缩、燃料组件——真正的卡脖子，西方产能高度集中、且受地缘影响。",
             "chokepoint": "浓缩铀(尤其 HALEU)西方产能极少，是新堆的硬约束。",
             "players": [{"ticker": "LEU", "name": "Centrus", "role": "美国浓缩铀/HALEU"}]},
            {"layer": "铀矿", "emoji": "⛏️", "tightness": "tight",
             "desc": "最上游原料，产地集中(哈萨克/加拿大/澳洲)，周期性极强。",
             "chokepoint": "优质铀矿产地高度集中，长期供给弹性低。",
             "players": [{"ticker": "CCJ", "name": "Cameco", "role": "全球铀矿龙头"}]},
        ],
        "takeaway": "存量核电运营(稀缺审批)和燃料/浓缩(西方产能极少)是真卡点；SMR 多在'讲故事'阶段，估值与兑现要分开看。",
    },
    {
        "key": "ev", "name": "电动汽车", "emoji": "🚗", "category": "新能源车",
        "hook": "整车在打价格战，利润正悄悄往电池、电池材料和芯片转移。",
        "demand": "全球电动车销量 + 单车带电量",
        "layers": [
            {"layer": "整车", "emoji": "🚙", "tightness": "loose",
             "desc": "品牌、产能、渠道。价格战激烈、利润被挤压。",
             "chokepoint": "", "players": [{"ticker": "TSLA", "name": "特斯拉", "role": "龙头+能源"},
                                          {"ticker": "BYDDY", "name": "比亚迪", "role": "垂直整合(ADR)"}]},
            {"layer": "动力电池", "emoji": "🔋", "tightness": "tight",
             "desc": "整车成本的 ~40%，技术与规模壁垒高，少数巨头主导。",
             "chokepoint": "宁德时代/LG/松下等少数厂吃下大部分产能，议价权强。",
             "players": [{"ticker": "TSLA", "name": "特斯拉", "role": "自研+采购"},
                         {"ticker": "PCRFY", "name": "松下", "role": "电池(ADR)"}]},
            {"layer": "电池材料", "emoji": "🧪", "tightness": "medium",
             "desc": "正极、负极、电解液、隔膜——化工属性，部分环节有壁垒。",
             "chokepoint": "高端隔膜、正极前驱体有技术壁垒；多数材料偏周期。",
             "players": [{"ticker": "ALB", "name": "Albemarle", "role": "锂"}]},
            {"layer": "关键矿产", "emoji": "⛏️", "tightness": "tight",
             "desc": "锂、镍、钴——产地集中、加工更集中(中国主导精炼)。",
             "chokepoint": "锂/钴精炼产能高度集中，是西方供应链的地缘软肋。",
             "players": [{"ticker": "ALB", "name": "Albemarle", "role": "锂矿+加工"}]},
            {"layer": "功率半导体", "emoji": "🔌", "tightness": "tight",
             "desc": "电控/逆变的碳化硅(SiC)器件，决定续航与快充，技术壁垒高。",
             "chokepoint": "车规级 SiC 衬底+器件良率是壁垒，少数厂领先。",
             "players": [{"ticker": "ON", "name": "安森美", "role": "车规 SiC"},
                         {"ticker": "STM", "name": "意法半导体", "role": "SiC(ADR)"}]},
        ],
        "takeaway": "整车是红海；利润正向电池、关键矿产精炼(地缘卡点)、车规 SiC 功率半导体转移。看链条别只盯整车。",
    },
    {
        "key": "humanoid", "name": "人形机器人", "emoji": "🦾", "category": "AI / 机器人",
        "researched": True,
        "hook": "整机还没量产，但'关节'里的减速器、丝杠、力矩传感器已经把脖子卡住了——而且代表厂大多在中日，不在美股。",
        "demand": "人形机器人量产台数（2026 起步；单机约 14 根行星滚柱丝杠 + 多个旋转/线性关节）",
        "layers": [
            {"layer": "整机 / 品牌", "emoji": "🤖", "tightness": "medium",
             "desc": "造整机、定方案、跑量产。处于极早期，估值高度依赖兑现预期。",
             "chokepoint": "",
             "players": [{"ticker": "TSLA", "name": "特斯拉", "role": "Optimus，自研为主 + 外采"},
                         {"name": "Unitree 宇树", "role": "中国整机龙头(未上市)"},
                         {"name": "Figure AI", "role": "美国整机(未上市)"}]},
            {"layer": "大脑 · 算力与仿真", "emoji": "🧠", "tightness": "tight",
             "desc": "机器人的'大脑'：边缘 AI 推理芯片 + 训练/仿真平台。英伟达在的是这一层，不是关节那一层。",
             "chokepoint": "英伟达 Jetson Thor 边缘算力 + Isaac GR00T 仿真与基础模型平台近乎全栈主导——这才是 NVDA 在人形里的真实位置。",
             "players": [{"ticker": "NVDA", "name": "英伟达", "role": "Jetson Thor 算力 + Isaac GR00T 平台"},
                         {"ticker": "QCOM", "name": "高通", "role": "边缘机器人 SoC"}]},
            {"layer": "关节执行器总成 (Tier-0.5)", "emoji": "🦿", "tightness": "tight",
             "desc": "把电机+减速器+丝杠+力矩传感器+控制集成成'关节模组'，是整机最贵的部分，深度绑定整机厂。",
             "chokepoint": "三花智控拿下马斯克约 6.85 亿美元关节模组订单、2026 交付；拓普集团是特斯拉 Tier-0.5 总成厂。",
             "players": [{"ticker": "002050.SZ", "name": "三花智控", "role": "关节模组核心供应商(A股)"},
                         {"ticker": "601689.SS", "name": "拓普集团", "role": "线性/旋转执行器总成(A股)"}]},
            {"layer": "谐波 / RV 减速器", "emoji": "⚙️", "tightness": "tight",
             "desc": "决定关节精度与寿命，最难最贵的精密件之一。日本长期主导，中国正快速国产替代。",
             "chokepoint": "谐波减速器精度与产能是真瓶颈：绿的谐波已过特斯拉验证、价格仅日系 40-60%，但顶尖工艺仍在日本(哈默纳科/纳博)。",
             "players": [{"ticker": "688017.SS", "name": "绿的谐波", "role": "国产谐波减速器龙头(A股·过特斯拉验证)"},
                         {"name": "哈默纳科 Harmonic Drive", "role": "谐波减速器全球龙头(日本 6324.T，无美股)"},
                         {"name": "纳博特斯克 Nabtesco", "role": "RV 减速器主导(日本，无美股)"}]},
            {"layer": "行星滚柱丝杠", "emoji": "🔩", "tightness": "tight",
             "desc": "把电机旋转变成直线推力的核心件，人形线性关节专用。单机约 14 根、每根 $1,350-2,700，极贵。",
             "chokepoint": "行星滚柱丝杠精度与良率是硬瓶颈；五洲新春等国产正放量(2025 股价 +183%)，高端仍看瑞士 Rollvis。",
             "players": [{"ticker": "603667.SS", "name": "五洲新春", "role": "行星滚柱丝杠(A股·放量)"},
                         {"name": "新剑传动 XJ", "role": "滚柱丝杠百万级产线(中国，未上市)"},
                         {"name": "Rollvis / GSA", "role": "高端滚柱丝杠(瑞士，未上市)"}]},
            {"layer": "无框 / 空心杯电机", "emoji": "🧲", "tightness": "tight",
             "desc": "关节的'肌肉'：无框力矩电机 + 空心杯电机，功率密度与一致性是壁垒。",
             "chokepoint": "高端无框/空心杯电机欧美日主导：AMETEK 空心杯全球前三，Allient 做无框力矩电机。",
             "players": [{"ticker": "AME", "name": "AMETEK", "role": "空心杯电机(全球前三)"},
                         {"ticker": "ALNT", "name": "Allient", "role": "无框力矩电机"},
                         {"ticker": "603728.SS", "name": "鸣志电器", "role": "运动控制电机(A股)"}]},
            {"layer": "六维力 / 力矩传感器", "emoji": "📡", "tightness": "tight",
             "desc": "让机器人'感觉到力'，灵巧操作与安全的关键，精度 + 量产双壁垒。",
             "chokepoint": "六维力矩传感器精度与量产仅少数厂：柯力传感等国产进入特斯拉验证，海外 ATI/Bota 主导。",
             "players": [{"ticker": "603662.SS", "name": "柯力传感", "role": "六维力传感器(A股·进特斯拉验证)"},
                         {"name": "ATI / Bota Systems", "role": "六维力传感器(美/瑞士，未上市)"}]},
        ],
        "takeaway": "真正卡脖子的是减速器、行星滚柱丝杠、六维力矩传感器这些精密件——而且代表厂大多是中国 A 股(绿的谐波/五洲新春/三花/拓普/柯力)和日本(哈默纳科/纳博)。美股能直接买到的主要只有'大脑'(NVDA/QCOM)和少数电机(AMETEK/Allient)。整机在讲故事，钱在不起眼的精密传动件上。",
    },
    {
        "key": "ai_health", "name": "AI 医疗", "emoji": "🧬", "category": "AI / 医疗",
        "hook": "AI 制药很性感，但能真正卡住别人的，是仪器、试剂和数据。",
        "demand": "新药研发效率 + 精准诊断需求",
        "layers": [
            {"layer": "AI 制药/诊断应用", "emoji": "💊", "tightness": "medium",
             "desc": "用 AI 发现靶点、设计分子、辅助诊断。前景大但兑现慢、监管严。",
             "chokepoint": "", "players": [{"ticker": "TEM", "name": "Tempus AI", "role": "肿瘤数据+诊断"},
                                          {"ticker": "RXRX", "name": "Recursion", "role": "AI 药物发现(高风险)"}]},
            {"layer": "基因测序", "emoji": "🧫", "tightness": "tight",
             "desc": "测序平台是 AI 医疗的'数据入口'，装机即锁定试剂消费。",
             "chokepoint": "测序仪市场高度集中，Illumina 长期主导(剃须刀-刀片模式)。",
             "players": [{"ticker": "ILMN", "name": "Illumina", "role": "基因测序平台"}]},
            {"layer": "生命科学仪器", "emoji": "🔬", "tightness": "tight",
             "desc": "质谱、流式、显微等高端仪器+耗材，研发离不开。",
             "chokepoint": "高端仪器+配套耗材壁垒高，少数巨头主导。",
             "players": [{"ticker": "TMO", "name": "赛默飞", "role": "仪器+耗材龙头"},
                         {"ticker": "DHR", "name": "丹纳赫", "role": "生命科学平台"}]},
            {"layer": "CXO 外包", "emoji": "🧴", "tightness": "medium",
             "desc": "研发/生产外包，承接 AI 药企的湿实验与产能。",
             "chokepoint": "", "players": [{"ticker": "IQV", "name": "IQVIA", "role": "CRO+医疗数据"}]},
            {"layer": "医疗数据", "emoji": "🗂️", "tightness": "tight",
             "desc": "真实世界数据/基因组数据，是训练医疗 AI 的'原油'，合规壁垒高。",
             "chokepoint": "高质量、合规、有标注的医疗数据极稀缺，是隐形护城河。",
             "players": [{"ticker": "TEM", "name": "Tempus", "role": "肿瘤多模态数据"}]},
        ],
        "takeaway": "AI 制药应用风险高、兑现慢；更稳的卡点在测序平台(刀片模式)、高端仪器耗材、和合规医疗数据。",
    },
    {
        "key": "quantum", "name": "量子计算", "emoji": "⚛️", "category": "前沿计算",
        "hook": "最热的纯量子股最危险——真正受益的可能是'卖配套'的老牌公司。",
        "demand": "可纠错量子比特数（仍在极早期）",
        "layers": [
            {"layer": "纯量子整机", "emoji": "🧊", "tightness": "medium",
             "desc": "纯标的，故事性极强但商业化遥远、烧钱、波动巨大。",
             "chokepoint": "", "players": [{"ticker": "IONQ", "name": "IonQ", "role": "离子阱(高风险高波动)"},
                                          {"ticker": "RGTI", "name": "Rigetti", "role": "超导(高风险)"}]},
            {"layer": "科技巨头量子部门", "emoji": "🏢", "tightness": "medium",
             "desc": "用云+资金长期投入，是更'抗摔'的量子敞口。",
             "chokepoint": "", "players": [{"ticker": "IBM", "name": "IBM", "role": "超导路线领先"},
                                          {"ticker": "GOOGL", "name": "谷歌", "role": "Willow 芯片"}]},
            {"layer": "低温与控制", "emoji": "❄️", "tightness": "tight",
             "desc": "稀释制冷机、微波控制电子——多数量子机绕不开的'水电煤'。",
             "chokepoint": "稀释制冷机供给极集中(芬兰 Bluefors 等)，是隐形卡点。",
             "players": [{"name": "Bluefors", "role": "稀释制冷机(私有,无美股)"}]},
            {"layer": "光子/元件", "emoji": "🔦", "tightness": "tight",
             "desc": "激光、光子器件、特种光学，量子与光通信共用。",
             "chokepoint": "高端激光与光子器件少数厂主导。",
             "players": [{"ticker": "COHR", "name": "Coherent", "role": "激光/光子"}]},
            {"layer": "测试与制造", "emoji": "🛠️", "tightness": "tight",
             "desc": "量子芯片仍要靠半导体设备与精密测试。",
             "chokepoint": "精密测试与半导体设备仍是少数巨头。",
             "players": [{"ticker": "KEYS", "name": "是德科技", "role": "量子测试仪器"}]},
        ],
        "takeaway": "纯量子股波动巨大、商业化遥远；'抗摔'的敞口在巨头量子部门，更稳的是卖低温/激光/测试这些配套的——量子版'卖铲人'。",
    },
    {
        "key": "space", "name": "太空经济", "emoji": "🛰️", "category": "太空",
        "hook": "发射成本崩了，价值正从'火箭'转向'天上的星座'和'地面的应用'。",
        "demand": "在轨卫星数 + 卫星带宽/数据需求",
        "layers": [
            {"layer": "应用与服务", "emoji": "📶", "tightness": "medium",
             "desc": "卫星通信、对地观测、导航增强——最贴近收入的下游。",
             "chokepoint": "", "players": [{"ticker": "ASTS", "name": "AST SpaceMobile", "role": "卫星直连手机(高风险)"},
                                          {"ticker": "IRDM", "name": "Iridium", "role": "卫星通信(有现金流)"}]},
            {"layer": "卫星制造", "emoji": "🛰️", "tightness": "medium",
             "desc": "造卫星与星座，正从'定制'走向'批量'。",
             "chokepoint": "", "players": [{"ticker": "RKLB", "name": "Rocket Lab", "role": "火箭+卫星制造"}]},
            {"layer": "发射", "emoji": "🚀", "tightness": "tight",
             "desc": "把东西送上天。可复用火箭把成本打下来，门槛仍极高。",
             "chokepoint": "可复用重型运力高度集中(SpaceX 主导)，是事实上的总闸门。",
             "players": [{"ticker": "RKLB", "name": "Rocket Lab", "role": "小/中型发射"}]},
            {"layer": "关键部件", "emoji": "🔧", "tightness": "tight",
             "desc": "星载电子、推进、太阳能帆板、特种连接器——航天级壁垒。",
             "chokepoint": "航天级元器件需长期认证(时间+可靠性壁垒)，玩家少。",
             "players": [{"ticker": "HEI", "name": "HEICO", "role": "航空航天部件"},
                         {"ticker": "RTX", "name": "RTX", "role": "航天系统"}]},
            {"layer": "国防与政府订单", "emoji": "🏛️", "tightness": "tight",
             "desc": "政府/军方是最大、最稳的付款方，订单壁垒高。",
             "chokepoint": "安全级订单需资质+长期关系，新进入者极难。",
             "players": [{"ticker": "LMT", "name": "洛克希德", "role": "航天/国防"}]},
        ],
        "takeaway": "发射被 SpaceX(未上市)主导；可投的相对稳的点在有现金流的卫星通信、发射小弟 Rocket Lab、和航天级部件(认证壁垒)。纯故事股波动大。",
    },
    {
        "key": "battery", "name": "储能与电池", "emoji": "🔋", "category": "清洁能源",
        "hook": "电池单体在打价格战，钱在'系统集成'和'上游材料/设备'两头。",
        "demand": "电网储能 + 户用储能装机（GWh）",
        "layers": [
            {"layer": "储能系统集成", "emoji": "📦", "tightness": "medium",
             "desc": "把电芯、PCS、温控、软件打包成电站，带项目和服务粘性。",
             "chokepoint": "", "players": [{"ticker": "TSLA", "name": "特斯拉", "role": "Megapack"},
                                          {"ticker": "FLNC", "name": "Fluence", "role": "电网储能集成"}]},
            {"layer": "功率电子 PCS", "emoji": "🔄", "tightness": "medium",
             "desc": "储能变流器，技术含量比电芯高。",
             "chokepoint": "", "players": [{"ticker": "ENPH", "name": "Enphase", "role": "户储"}]},
            {"layer": "电芯", "emoji": "🔋", "tightness": "tight",
             "desc": "LFP/钠电等，规模与良率壁垒，少数巨头主导。",
             "chokepoint": "电芯产能集中在中韩少数巨头，议价权强。",
             "players": [{"ticker": "TSLA", "name": "特斯拉", "role": "自研+采购"}]},
            {"layer": "材料", "emoji": "🧪", "tightness": "medium",
             "desc": "正负极、电解液、隔膜，偏化工与周期。",
             "chokepoint": "高端隔膜/电解液添加剂有壁垒。",
             "players": [{"ticker": "ALB", "name": "Albemarle", "role": "锂"}]},
            {"layer": "设备", "emoji": "🛠️", "tightness": "tight",
             "desc": "造电芯的涂布/卷绕/化成设备——又是'卖铲人'。",
             "chokepoint": "高端锂电设备少数厂主导，扩产周期里最稳。",
             "players": [{"ticker": "AMAT", "name": "应用材料", "role": "(部分电池设备)"}]},
        ],
        "takeaway": "电芯红海(虽集中但价格战)；相对好的位置在系统集成(服务粘性)和上游设备/关键材料(卖铲)。",
    },
    {
        "key": "semicap", "name": "半导体设备", "emoji": "🔬", "category": "半导体",
        "hook": "整条科技业最硬的卡脖子环节，几乎全在这里。",
        "demand": "全球晶圆厂资本开支（WFE）",
        "layers": [
            {"layer": "晶圆代工/IDM", "emoji": "🏭", "tightness": "tight",
             "desc": "买设备造芯片的需求方，先进制程高度集中。",
             "chokepoint": "先进制程实质只剩台积电/三星/英特尔三家。",
             "players": [{"ticker": "TSM", "name": "台积电", "role": "先进制程(ADR)"},
                         {"ticker": "INTC", "name": "英特尔", "role": "IDM+代工"}]},
            {"layer": "光刻", "emoji": "🔦", "tightness": "tight",
             "desc": "把电路'印'到硅片上，最尖端的咽喉。",
             "chokepoint": "EUV 光刻 ASML 全球独家——科技业最强单点卡脖子。",
             "players": [{"ticker": "ASML", "name": "ASML", "role": "EUV 独家(ADR)"}]},
            {"layer": "刻蚀/沉积", "emoji": "⚗️", "tightness": "tight",
             "desc": "把图形雕出来、把薄膜长上去，寡头垄断。",
             "chokepoint": "刻蚀/沉积是 LAM/AMAT/TEL 的寡头局。",
             "players": [{"ticker": "LRCX", "name": "泛林", "role": "刻蚀龙头"},
                         {"ticker": "AMAT", "name": "应用材料", "role": "沉积/多工艺"}]},
            {"layer": "量测检测", "emoji": "📏", "tightness": "tight",
             "desc": "在线检查良率，越先进越离不开，KLA 近乎垄断。",
             "chokepoint": "工艺控制量测 KLA 一家独大。",
             "players": [{"ticker": "KLAC", "name": "科磊", "role": "量测检测垄断"}]},
            {"layer": "材料与耗材", "emoji": "🧴", "tightness": "tight",
             "desc": "光刻胶、高纯气体、过滤、CMP 抛光液——消费型，旱涝保收。",
             "chokepoint": "高纯材料/光刻胶日本主导，Entegris 等过滤纯化卡位。",
             "players": [{"ticker": "ENTG", "name": "Entegris", "role": "高纯材料/过滤"}]},
        ],
        "takeaway": "这条链几乎每层都 tight：EUV(ASML 独家)、刻蚀沉积寡头、量测(KLA)、高纯材料(日本/Entegris)。全行业最硬的卡脖子集合。",
    },
    {
        "key": "grid", "name": "电网与输配电", "emoji": "⚡", "category": "电力",
        "hook": "新能源和 AI 都要并网，但电网老化、变压器一货难求。",
        "demand": "电力负荷增长 + 新能源并网 + 电网更新",
        "layers": [
            {"layer": "公用事业/电网公司", "emoji": "🏢", "tightness": "medium",
             "desc": "运营电网卖电，受监管、现金流稳，但增长慢。",
             "chokepoint": "", "players": [{"ticker": "NEE", "name": "NextEra", "role": "公用+清洁电力"},
                                          {"ticker": "AEP", "name": "American Electric", "role": "输电网"}]},
            {"layer": "电网设备", "emoji": "🔌", "tightness": "tight",
             "desc": "变压器、开关、保护——AI/新能源潮下严重供不应求。",
             "chokepoint": "大型电力变压器全球产能紧、交期长达数年，硬卡点。",
             "players": [{"ticker": "ETN", "name": "伊顿", "role": "电力管理设备"},
                         {"ticker": "GEV", "name": "GE Vernova", "role": "电网/电气化"}]},
            {"layer": "工程与建设", "emoji": "🏗️", "tightness": "medium",
             "desc": "输电线路、变电站建设，订单饱满。",
             "chokepoint": "", "players": [{"ticker": "PWR", "name": "Quanta", "role": "电网工程龙头"}]},
            {"layer": "连接与元件", "emoji": "🔗", "tightness": "tight",
             "desc": "高压连接器、互感器、特种电缆——细分卡位。",
             "chokepoint": "高压/特种连接器认证壁垒高。",
             "players": [{"ticker": "APH", "name": "安费诺", "role": "高速/高压连接器"}]},
            {"layer": "原材料", "emoji": "🪨", "tightness": "medium",
             "desc": "铜、取向硅钢——变压器的关键材料，周期+紧缺。",
             "chokepoint": "取向硅钢产能集中，铜受周期影响。",
             "players": [{"ticker": "FCX", "name": "Freeport", "role": "铜矿"}]},
        ],
        "takeaway": "电网公司增长慢；真正紧的是电网设备(变压器交期数年)和工程龙头——AI 抢电+新能源并网的'卖铲人'。",
    },
    {
        "key": "defense", "name": "国防军工", "emoji": "🛡️", "category": "国防",
        "hook": "地缘紧张推升预算，但订单壁垒和'弹药耗材'才是稳定现金牛。",
        "demand": "国防预算 + 弹药/导弹补库存",
        "layers": [
            {"layer": "主承包商", "emoji": "✈️", "tightness": "tight",
             "desc": "整机/整弹系统集成，与政府长期绑定，护城河深。",
             "chokepoint": "主战平台只有少数承包商能做，关系+资质壁垒极高。",
             "players": [{"ticker": "LMT", "name": "洛克希德", "role": "战机/导弹"},
                         {"ticker": "RTX", "name": "RTX", "role": "导弹/发动机"}]},
            {"layer": "导弹与弹药", "emoji": "🚀", "tightness": "tight",
             "desc": "消耗品属性，冲突中持续补库存，现金流稳。",
             "chokepoint": "固体火箭发动机等产能紧、产线难快速扩。",
             "players": [{"ticker": "LMT", "name": "洛克希德", "role": "导弹"},
                         {"ticker": "NOC", "name": "诺斯罗普", "role": "固体推进/弹药"}]},
            {"layer": "电子与传感", "emoji": "📡", "tightness": "tight",
             "desc": "雷达、电子战、夜视、制导芯片——技术与认证双壁垒。",
             "chokepoint": "国防级电子需特种认证，玩家受限。",
             "players": [{"ticker": "RTX", "name": "RTX", "role": "雷达/电子战"},
                         {"ticker": "LHX", "name": "L3Harris", "role": "战术通信/传感"}]},
            {"layer": "无人系统/新势力", "emoji": "🛸", "tightness": "medium",
             "desc": "软件定义的无人机/自主系统，挑战老牌承包商。",
             "chokepoint": "", "players": [{"ticker": "AVAV", "name": "AeroVironment", "role": "无人机"},
                                          {"ticker": "PLTR", "name": "Palantir", "role": "国防软件/AI"}]},
            {"layer": "特种材料", "emoji": "🧱", "tightness": "tight",
             "desc": "钛、特种合金、稀土磁材——上游受地缘约束。",
             "chokepoint": "稀土磁材精炼中国主导，是西方军工软肋。",
             "players": [{"ticker": "MP", "name": "MP Materials", "role": "美国稀土"}]},
        ],
        "takeaway": "主承包商(资质护城河)和弹药耗材(持续补库)是稳定现金牛；上游稀土磁材是地缘卡点。无人系统是变量。",
    },
    {
        "key": "cyber", "name": "网络安全", "emoji": "🔐", "category": "软件",
        "hook": "AI 既是新攻击面也是新卖点，平台化的龙头吃下越来越多份额。",
        "demand": "企业安全支出（随上云与 AI 上升）",
        "layers": [
            {"layer": "安全平台", "emoji": "🛡️", "tightness": "tight",
             "desc": "端点/云/SIEM 一体化平台，切换成本高、粘性强。",
             "chokepoint": "平台化龙头靠数据飞轮+集成形成强锁定。",
             "players": [{"ticker": "CRWD", "name": "CrowdStrike", "role": "端点/平台"},
                         {"ticker": "PANW", "name": "Palo Alto", "role": "网络/平台化"}]},
            {"layer": "身份与零信任", "emoji": "🪪", "tightness": "medium",
             "desc": "身份是新边界，AI 时代访问控制更关键。",
             "chokepoint": "", "players": [{"ticker": "ZS", "name": "Zscaler", "role": "零信任"},
                                          {"ticker": "OKTA", "name": "Okta", "role": "身份"}]},
            {"layer": "云与数据安全", "emoji": "☁️", "tightness": "medium",
             "desc": "保护云上工作负载与数据，增长快。",
             "chokepoint": "", "players": [{"ticker": "PANW", "name": "Palo Alto", "role": "云安全(Prisma)"}]},
            {"layer": "基础设施", "emoji": "🌐", "tightness": "tight",
             "desc": "CDN/边缘/DDoS 防护，规模即壁垒。",
             "chokepoint": "全球边缘网络规模是少数厂的护城河。",
             "players": [{"ticker": "NET", "name": "Cloudflare", "role": "边缘/安全"}]},
        ],
        "takeaway": "钱在平台化龙头(切换成本+数据飞轮)和规模型基础设施。点状工具易被平台吞并——这条链是'强者恒强'。",
    },
    {
        "key": "autonomous", "name": "自动驾驶", "emoji": "🛞", "category": "AI / 出行",
        "hook": "Robotaxi 还在烧钱，但'眼睛'和'大脑'的供应商已经先赚到钱。",
        "demand": "L4 自动驾驶里程 + 高阶辅助驾驶渗透率",
        "layers": [
            {"layer": "Robotaxi/整车方案", "emoji": "🚕", "tightness": "medium",
             "desc": "运营或全栈方案，重资金、长周期、监管不确定。",
             "chokepoint": "", "players": [{"ticker": "TSLA", "name": "特斯拉", "role": "FSD/纯视觉"},
                                          {"ticker": "GOOGL", "name": "谷歌", "role": "Waymo"}]},
            {"layer": "自动驾驶芯片", "emoji": "🧠", "tightness": "tight",
             "desc": "车载高算力 SoC，是'大脑'，少数厂主导。",
             "chokepoint": "高阶自动驾驶 SoC 英伟达/高通+特斯拉自研主导。",
             "players": [{"ticker": "NVDA", "name": "英伟达", "role": "Drive 平台"},
                         {"ticker": "QCOM", "name": "高通", "role": "座舱+驾驶"}]},
            {"layer": "传感器(激光雷达/雷达)", "emoji": "📡", "tightness": "medium",
             "desc": "'眼睛'。激光雷达降价中、竞争激烈，毫米波雷达更成熟。",
             "chokepoint": "", "players": [{"ticker": "MBLY", "name": "Mobileye", "role": "视觉+方案"}]},
            {"layer": "高精地图/数据", "emoji": "🗺️", "tightness": "tight",
             "desc": "数据闭环与高精地图是壁垒，越跑越强。",
             "chokepoint": "海量真实驾驶数据闭环难复制，是隐形护城河。",
             "players": [{"ticker": "TSLA", "name": "特斯拉", "role": "车队数据闭环"}]},
            {"layer": "连接器与线束", "emoji": "🔗", "tightness": "tight",
             "desc": "高速车载连接器/线束，单车用量随智能化暴增。",
             "chokepoint": "高速车规连接器寡头(安费诺/TE)。",
             "players": [{"ticker": "APH", "name": "安费诺", "role": "车载高速连接器"}]},
        ],
        "takeaway": "Robotaxi 烧钱、监管不定；先赚到钱的是自动驾驶芯片(大脑)、数据闭环(护城河)、和高速连接器(用量暴增的卖铲人)。",
    },
    {
        "key": "hydrogen", "name": "氢能", "emoji": "💧", "category": "清洁能源",
        "hook": "最性感、也最容易亏钱的赛道——先看清谁有真订单、谁在烧钱。",
        "demand": "绿氢产量 + 燃料电池/工业脱碳需求",
        "layers": [
            {"layer": "绿氢生产/项目", "emoji": "🏭", "tightness": "medium",
             "desc": "电解水制氢项目，高度依赖补贴与电价，多数尚未盈利。",
             "chokepoint": "", "players": [{"ticker": "PLUG", "name": "Plug Power", "role": "电解槽+绿氢(长期烧钱)"}]},
            {"layer": "电解槽/燃料电池", "emoji": "🔋", "tightness": "medium",
             "desc": "核心设备，技术路线未收敛，竞争分散。",
             "chokepoint": "", "players": [{"ticker": "BE", "name": "Bloom Energy", "role": "固体氧化物燃料电池"}]},
            {"layer": "工业气体巨头", "emoji": "🫧", "tightness": "tight",
             "desc": "氢的'隐形赢家'——已有管网、客户、现金流，做氢是顺手生意。",
             "chokepoint": "工业气体寡头(管网+长协)是真正稳的氢敞口。",
             "players": [{"ticker": "LIN", "name": "林德", "role": "工业气体龙头"},
                         {"ticker": "APD", "name": "空气产品", "role": "氢气供应"}]},
            {"layer": "催化剂/材料", "emoji": "🧪", "tightness": "tight",
             "desc": "铂族金属催化剂、质子膜——上游材料壁垒高、产地集中。",
             "chokepoint": "铂族金属产地极集中(南非/俄罗斯)，是上游卡点。",
             "players": [{"name": "Johnson Matthey", "role": "催化剂(英国,无美股)"}]},
        ],
        "takeaway": "纯氢标的(Plug 等)长期烧钱、风险高；真正稳的氢敞口是工业气体巨头(已有管网客户现金流)。别被故事冲昏头。",
    },
    {
        "key": "advanced_packaging", "name": "先进封装与 HBM", "emoji": "📦", "category": "半导体",
        "hook": "摩尔定律放缓后，'怎么把芯片叠起来'成了 AI 芯片的新瓶颈。",
        "demand": "AI 芯片对 HBM 带宽 + 先进封装产能的需求",
        "layers": [
            {"layer": "AI 芯片设计", "emoji": "🧠", "tightness": "tight",
             "desc": "需求方，要把 GPU 与 HBM 用先进封装集成。",
             "chokepoint": "英伟达等的需求直接决定先进封装与 HBM 的扩产节奏。",
             "players": [{"ticker": "NVDA", "name": "英伟达", "role": "拉动需求"},
                         {"ticker": "AMD", "name": "AMD", "role": "chiplet 先行"}]},
            {"layer": "HBM 存储", "emoji": "🧱", "tightness": "tight",
             "desc": "高带宽内存，AI 芯片的'喂食管'，三家寡头、供不应求。",
             "chokepoint": "HBM 仅 SK海力士/三星/美光三家，先进产能被抢空。",
             "players": [{"ticker": "MU", "name": "美光", "role": "HBM 三强之一"}]},
            {"layer": "先进封装(CoWoS)", "emoji": "🏭", "tightness": "tight",
             "desc": "把 GPU 和 HBM 封在一起，台积电 CoWoS 是总闸门。",
             "chokepoint": "CoWoS 产能是整个 AI 芯片供给的瓶颈，台积电主导。",
             "players": [{"ticker": "TSM", "name": "台积电", "role": "CoWoS 先进封装(ADR)"}]},
            {"layer": "封装设备", "emoji": "🛠️", "tightness": "tight",
             "desc": "混合键合(hybrid bonding)等设备，决定叠装精度，玩家极少。",
             "chokepoint": "混合键合设备 BE Semiconductor(BESI)等少数厂卡位。",
             "players": [{"ticker": "BESIY", "name": "BE Semiconductor", "role": "混合键合设备(ADR)"}]},
            {"layer": "载板与材料", "emoji": "🧩", "tightness": "tight",
             "desc": "ABF 载板、特种基板——先进封装的'地基'，日本/台湾主导。",
             "chokepoint": "ABF 载板(Ibiden/Shinko)近寡头，长期紧缺。",
             "players": [{"name": "Ibiden", "role": "ABF 载板(日本,无美股)"}]},
        ],
        "takeaway": "这是 AI 算力的新瓶颈集合：HBM(三寡头被抢空)、CoWoS(台积电总闸门)、混合键合设备(BESI)、ABF 载板(日本寡头)。几乎层层 tight。",
    },
]


import json as _json
import pathlib as _pathlib

from ..cache import cached as _cached

_DEEP_PATH = _pathlib.Path(__file__).resolve().parent / "sectors_deep.json"
_TRANS_PATH = _pathlib.Path(__file__).resolve().parent / "transmission.json"


def _load_deep() -> dict:
    """深度研究产出(10段框架)按 key 覆盖内联浅版；缺失则保留内联。"""
    try:
        return {s["key"]: s for s in _json.loads(_DEEP_PATH.read_text(encoding="utf-8"))}
    except Exception:
        return {}


def _load_transmission() -> dict:
    """实证传导(本机 Tushare 批处理产出)按 key 附到对应链上；只读静态 JSON。"""
    try:
        return _json.loads(_TRANS_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {}


@_cached(1800)
def get_sectors() -> dict:
    deep = _load_deep()
    trans = _load_transmission()
    merged = []
    for s in SECTORS:
        m = deep.get(s["key"], s)
        if s["key"] in trans:
            m = {**m, "transmission": trans[s["key"]]}
        merged.append(m)
    # 仅存在于深研产物、不在内联 SECTORS 的链（如商品周期链 gold/aluminum）
    _inline = {s["key"] for s in SECTORS}
    for k, dv in deep.items():
        if k not in _inline:
            merged.append({**dv, "transmission": trans[k]} if k in trans else dv)
    return {
        "sectors": merged,
        "n": len(merged),
        "tightness_legend": {
            "tight": "卡脖子/少数玩家/难替代——定价权和超额收益更可能藏在这",
            "medium": "有壁垒但有竞争",
            "loose": "充分竞争/价格战——别在这里卷",
        },
        "disclaimer": "教育性结构地图，代表性公司仅作举例、非推荐；基于公开认知可能过时或有误，请自行核实。供应链拆解不构成投资建议。",
    }
